from django.core.management.base import BaseCommand
from products.models import Product
from decimal import Decimal


class Command(BaseCommand):
    help = 'Seed the database with comprehensive product catalog (60+ items across 12 categories)'

    def handle(self, *args, **options):
        products = [
            # 1. Electronics (6 items)
            {
                'name': 'Sony WH-1000XM5 Wireless Noise Canceling Headphones',
                'brand': 'Sony',
                'description': 'Industry-leading noise canceling with two processors and 8 microphones. Magnificent audio quality with 30-hour battery life, ultra-comfortable lightweight design, and crystal-clear hands-free calling.',
                'price': Decimal('29990.00'),
                'category': 'electronics',
                'stock': 35,
                'is_featured': True,
                'discount_percent': 12,
                'rating': Decimal('4.8'),
            },
            {
                'name': 'Apple iPad Air 11" M2 Chip 128GB',
                'brand': 'Apple',
                'description': 'Stunning Liquid Retina display with True Tone and P3 wide color. Blazing-fast Apple M2 chip, 12MP Ultra Wide front camera with Center Stage, and superfast Wi-Fi 6E connectivity.',
                'price': Decimal('59900.00'),
                'category': 'electronics',
                'stock': 18,
                'is_featured': True,
                'discount_percent': 8,
                'rating': Decimal('4.9'),
            },
            {
                'name': 'Logitech MX Master 3S Wireless Performance Mouse',
                'brand': 'Logitech',
                'description': 'Quiet clicks, 8K DPI tracking on any surface including glass. MagSpeed electromagnetic scrolling delivers remarkable speed and precision with ultra-quiet operation.',
                'price': Decimal('9995.00'),
                'category': 'electronics',
                'stock': 42,
                'is_featured': False,
                'discount_percent': 15,
                'rating': Decimal('4.7'),
            },
            {
                'name': 'Samsung Odyssey OLED G8 34" Curved Gaming Monitor',
                'brand': 'Samsung',
                'description': 'Mesmerizing QD-OLED display with 0.03ms response time and 175Hz refresh rate. Neo Quantum Processor and Smart TV experience built right into the sleek metal frame.',
                'price': Decimal('94999.00'),
                'category': 'electronics',
                'stock': 10,
                'is_featured': True,
                'discount_percent': 18,
                'rating': Decimal('4.9'),
            },
            {
                'name': 'Bose SoundLink Revolve+ II Bluetooth Speaker',
                'brand': 'Bose',
                'description': 'True 360-degree sound for consistent, uniform coverage. Durable, water and dust-resistant design (IP55) with flexible fabric handle and up to 17 hours of battery life.',
                'price': Decimal('24500.00'),
                'category': 'electronics',
                'stock': 25,
                'is_featured': False,
                'discount_percent': 10,
                'rating': Decimal('4.6'),
            },
            {
                'name': 'Anker 737 Power Bank (PowerCore 24K) 140W',
                'brand': 'Anker',
                'description': 'Ultra-powerful 140W two-way fast charging with the latest Power Delivery 3.1 and bi-directional technology. Smart digital display shows output/input power and estimated recharge time.',
                'price': Decimal('13999.00'),
                'category': 'electronics',
                'stock': 30,
                'is_featured': False,
                'discount_percent': 20,
                'rating': Decimal('4.8'),
            },

            # 2. Fashion (6 items)
            {
                'name': 'Levi\'s Men\'s 511 Slim Fit Stretch Denim Jeans',
                'brand': 'Levi\'s',
                'description': 'A modern slim with room to move. Added stretch for all-day comfort and mobility. Crafted from sustainably sourced cotton with classic 5-pocket styling.',
                'price': Decimal('3299.00'),
                'category': 'fashion',
                'stock': 50,
                'is_featured': False,
                'discount_percent': 25,
                'rating': Decimal('4.4'),
            },
            {
                'name': 'Tommy Hilfiger Classic Oxford Button-Down Shirt',
                'brand': 'Tommy Hilfiger',
                'description': 'Tailored from 100% premium woven cotton with a classic button-down collar. Embroidered signature flag logo at chest. Breathable, crisp, and timeless.',
                'price': Decimal('4499.00'),
                'category': 'fashion',
                'stock': 40,
                'is_featured': True,
                'discount_percent': 20,
                'rating': Decimal('4.6'),
            },
            {
                'name': 'Nike Sportswear Club Fleece Pullover Hoodie',
                'brand': 'Nike',
                'description': 'Brushed-back fleece fabric feels soft and smooth against the skin. Ribbed hem and cuffs keep the shape, with an adjustable drawstring hood and kangaroo pocket.',
                'price': Decimal('3795.00'),
                'category': 'fashion',
                'stock': 65,
                'is_featured': False,
                'discount_percent': 15,
                'rating': Decimal('4.7'),
            },
            {
                'name': 'Zara Oversized Double-Breasted Trench Coat',
                'brand': 'Zara',
                'description': 'Sophisticated water-resistant cotton blend trench coat featuring wide notched lapels, belt with buckle, side pockets, and rear vent for refined seasonal layering.',
                'price': Decimal('7990.00'),
                'category': 'fashion',
                'stock': 20,
                'is_featured': False,
                'discount_percent': 10,
                'rating': Decimal('4.5'),
            },
            {
                'name': 'Puma Teveris Nitro Retro Running Sneakers',
                'brand': 'Puma',
                'description': 'Chunky retro 2000s runner silhouette infused with modern NITRO foam cushioning in the midsole for lightweight responsiveness and all-day street style.',
                'price': Decimal('5999.00'),
                'category': 'fashion',
                'stock': 35,
                'is_featured': False,
                'discount_percent': 30,
                'rating': Decimal('4.3'),
            },
            {
                'name': 'Ray-Ban Aviator Classic Polarized Sunglasses',
                'brand': 'Ray-Ban',
                'description': 'Timeless teardrop shape with crystal polarized green lenses and gold metal frames. 100% UV protection and exceptional optical clarity.',
                'price': Decimal('11590.00'),
                'category': 'fashion',
                'stock': 28,
                'is_featured': True,
                'discount_percent': 15,
                'rating': Decimal('4.8'),
            },

            # 3. Home & Kitchen (5 items)
            {
                'name': 'Philips Air Fryer XXL with Smart Sensing Technology',
                'brand': 'Philips',
                'description': 'Twin TurboStar technology removes excess fat while frying with little to no added oil. Huge 1.4kg capacity fits a whole chicken. Digital touch screen with preset recipes.',
                'price': Decimal('14999.00'),
                'category': 'home',
                'stock': 22,
                'is_featured': True,
                'discount_percent': 22,
                'rating': Decimal('4.7'),
            },
            {
                'name': 'Dyson V12 Detect Slim Cordless Vacuum Cleaner',
                'brand': 'Dyson',
                'description': 'Laser reveals invisible dust on hard floors. Piezo sensor continuously sizes and counts dust particles. Up to 60 minutes of fade-free suction with 3 power modes.',
                'price': Decimal('47900.00'),
                'category': 'home',
                'stock': 14,
                'is_featured': False,
                'discount_percent': 10,
                'rating': Decimal('4.8'),
            },
            {
                'name': 'Nespresso Vertuo Pop Espresso Machine',
                'brand': 'Nespresso',
                'description': 'Centrifusion technology gently brews fresh coffee with naturally formed crema. Compact, vibrant design compatible with 4 cup sizes from espresso to large mug.',
                'price': Decimal('16500.00'),
                'category': 'home',
                'stock': 20,
                'is_featured': False,
                'discount_percent': 15,
                'rating': Decimal('4.5'),
            },
            {
                'name': 'Prestige Deluxe Alpha Stainless Steel Pressure Cooker 5L',
                'brand': 'Prestige',
                'description': 'Alpha base induction bottom pressure cooker crafted from heavy-gauge stainless steel. Pressure indicator with unique controlled gasket release system for maximum safety.',
                'price': Decimal('2850.00'),
                'category': 'home',
                'stock': 55,
                'is_featured': False,
                'discount_percent': 25,
                'rating': Decimal('4.6'),
            },
            {
                'name': 'IKEA Strandmon Wing Chair in Velvet Dark Green',
                'brand': 'IKEA',
                'description': 'Classic wing chair silhouette with high back for neck support and deep seat cushions. Soft velvet upholstery with sturdy solid beech legs.',
                'price': Decimal('19990.00'),
                'category': 'home',
                'stock': 8,
                'is_featured': False,
                'discount_percent': 5,
                'rating': Decimal('4.6'),
            },

            # 4. Sports & Fitness (5 items)
            {
                'name': 'Decathlon Domyos Hex Dumbbells 20kg Pair',
                'brand': 'Decathlon',
                'description': 'Cast iron core with durable non-scratch rubber coating. Hexagonal shape prevents rolling on the floor. Ergonomic knurled chrome grip for secure hold.',
                'price': Decimal('5499.00'),
                'category': 'sports',
                'stock': 30,
                'is_featured': False,
                'discount_percent': 18,
                'rating': Decimal('4.7'),
            },
            {
                'name': 'Yonex Astrox 99 Pro Badminton Racket',
                'brand': 'Yonex',
                'description': 'Rotational Generator System with Namd graphite in the shaft for overpowering steep attacks. Extra slim shaft and Energy Boost Cap Plus for maximum flex.',
                'price': Decimal('14990.00'),
                'category': 'sports',
                'stock': 16,
                'is_featured': True,
                'discount_percent': 20,
                'rating': Decimal('4.9'),
            },
            {
                'name': 'Manduka PRO Yoga & Pilates Mat 6mm',
                'brand': 'Manduka',
                'description': 'High-density closed-cell cushion prevents sweat and moisture absorption. Unmatched joint protection and lifetime guarantee. OEKO-TEX certified emissions-free manufacturing.',
                'price': Decimal('9200.00'),
                'category': 'sports',
                'stock': 24,
                'is_featured': False,
                'discount_percent': 10,
                'rating': Decimal('4.8'),
            },
            {
                'name': 'Garmin Forerunner 265 GPS Running Smartwatch',
                'brand': 'Garmin',
                'description': 'Brilliant AMOLED touchscreen display with training readiness scores, HRV status, and daily suggested workouts. Up to 13 days battery life in smartwatch mode.',
                'price': Decimal('46490.00'),
                'category': 'sports',
                'stock': 12,
                'is_featured': False,
                'discount_percent': 8,
                'rating': Decimal('4.8'),
            },
            {
                'name': 'Spalding NBA Official Leather Game Basketball Size 7',
                'brand': 'Spalding',
                'description': 'Full-grain Horween leather cover with superior pebble texture and true bounce consistency for championship-level indoor hardwood play.',
                'price': Decimal('4299.00'),
                'category': 'sports',
                'stock': 40,
                'is_featured': False,
                'discount_percent': 15,
                'rating': Decimal('4.5'),
            },

            # 5. Books (5 items)
            {
                'name': 'Designing Data-Intensive Applications by Martin Kleppmann',
                'brand': 'O\'Reilly',
                'description': 'The definitive guide to the architecture of modern data systems. Deep dive into transactions, consensus, batch/stream processing, and distributed data storage.',
                'price': Decimal('1899.00'),
                'category': 'books',
                'stock': 75,
                'is_featured': True,
                'discount_percent': 20,
                'rating': Decimal('4.9'),
            },
            {
                'name': 'Atomic Habits by James Clear (Hardcover Edition)',
                'brand': 'Penguin Random House',
                'description': 'No matter your goals, Atomic Habits offers a proven framework for improving every day. Practical strategies to form good habits, break bad ones, and master tiny behaviors.',
                'price': Decimal('799.00'),
                'category': 'books',
                'stock': 120,
                'is_featured': False,
                'discount_percent': 35,
                'rating': Decimal('4.9'),
            },
            {
                'name': 'System Design Interview – An Insider\'s Guide Vol. 2',
                'brand': 'Independently Published',
                'description': 'Alex Xu & Sahn Lam present step-by-step solutions to real-world system design questions: Payment System, Digital Wallet, Stock Exchange, Live Streaming, and more.',
                'price': Decimal('2499.00'),
                'category': 'books',
                'stock': 50,
                'is_featured': False,
                'discount_percent': 10,
                'rating': Decimal('4.8'),
            },
            {
                'name': 'The Psychology of Money by Morgan Housel',
                'brand': 'Harriman House',
                'description': 'Timeless lessons on wealth, greed, and happiness. Doing well with money isn\'t necessarily about what you know. It\'s about how you behave.',
                'price': Decimal('450.00'),
                'category': 'books',
                'stock': 90,
                'is_featured': False,
                'discount_percent': 25,
                'rating': Decimal('4.7'),
            },
            {
                'name': 'Clean Code: A Handbook of Agile Software Craftsmanship',
                'brand': 'Prentice Hall',
                'description': 'Robert C. Martin (Uncle Bob) breaks down best agile coding practices, naming conventions, function architectures, and refactoring techniques to produce clean software.',
                'price': Decimal('1299.00'),
                'category': 'books',
                'stock': 60,
                'is_featured': False,
                'discount_percent': 15,
                'rating': Decimal('4.7'),
            },

            # 6. Accessories (5 items)
            {
                'name': 'Bellroy Hide & Seek Premium Leather Wallet',
                'brand': 'Bellroy',
                'description': 'Environmentally certified leather slim bifold with hidden coin and bill pouch, RFID protection, and capacity for up to 12 cards without pocket bulk.',
                'price': Decimal('6900.00'),
                'category': 'accessories',
                'stock': 35,
                'is_featured': False,
                'discount_percent': 10,
                'rating': Decimal('4.6'),
            },
            {
                'name': 'Peak Design Everyday Backpack V2 20L Charcoal',
                'brand': 'Peak Design',
                'description': 'Award-winning weatherproof 400D recycled nylon canvas daypack with MagLatch hardware, customizable FlexFold dividers, and dual side access.',
                'price': Decimal('24999.00'),
                'category': 'accessories',
                'stock': 15,
                'is_featured': True,
                'discount_percent': 12,
                'rating': Decimal('4.9'),
            },
            {
                'name': 'Fossil Grant Chronograph Luggage Leather Watch',
                'brand': 'Fossil',
                'description': 'Classic Roman numeral hour markers with chronograph sub-dials. Stainless steel 44mm case with rich amber leather strap and 50m water resistance.',
                'price': Decimal('11995.00'),
                'category': 'accessories',
                'stock': 28,
                'is_featured': False,
                'discount_percent': 30,
                'rating': Decimal('4.5'),
            },
            {
                'name': 'Keychron K2 V2 Wireless Mechanical Keyboard Palm Rest',
                'brand': 'Keychron',
                'description': 'Crafted from solid American walnut wood with polished ergonomic curvature. Provides superior wrist support during marathon typing and coding sessions.',
                'price': Decimal('2499.00'),
                'category': 'accessories',
                'stock': 45,
                'is_featured': False,
                'discount_percent': 15,
                'rating': Decimal('4.4'),
            },
            {
                'name': 'Orbitkey 2.0 Leather Key Organizer Espresso Brown',
                'brand': 'Orbitkey',
                'description': 'Transform messy key bunches into a silent, organized stack. Accommodates 2 to 7 keys with premium leather band and secure stainless steel locking mechanism.',
                'price': Decimal('3200.00'),
                'category': 'accessories',
                'stock': 50,
                'is_featured': False,
                'discount_percent': 20,
                'rating': Decimal('4.6'),
            },

            # 7. Beauty & Personal Care (5 items)
            {
                'name': 'Dyson Supersonic Hair Dryer Prussian Blue / Copper',
                'brand': 'Dyson',
                'description': 'Fast drying with no extreme heat. Intelligent heat control measures air temperature over 40 times a second. Includes 5 magnetic styling attachments.',
                'price': Decimal('34900.00'),
                'category': 'beauty',
                'stock': 18,
                'is_featured': True,
                'discount_percent': 10,
                'rating': Decimal('4.9'),
            },
            {
                'name': 'Estée Lauder Advanced Night Repair Serum 50ml',
                'brand': 'Estée Lauder',
                'description': 'Revolutionary Chronolux Power Signal Technology reduces the look of multiple signs of aging. Skin feels smoother, less lined, and radiant.',
                'price': Decimal('8900.00'),
                'category': 'beauty',
                'stock': 30,
                'is_featured': False,
                'discount_percent': 15,
                'rating': Decimal('4.8'),
            },
            {
                'name': 'Oral-B iO Series 9 Electric Toothbrush with Magnetic Drive',
                'brand': 'Oral-B',
                'description': 'Revolutionary iO magnetic technology for a professional clean feeling and gentle brushing. 3D teeth tracking with AI to monitor brushing across 16 zones.',
                'price': Decimal('19999.00'),
                'category': 'beauty',
                'stock': 20,
                'is_featured': False,
                'discount_percent': 25,
                'rating': Decimal('4.7'),
            },
            {
                'name': 'The Ordinary Niacinamide 10% + Zinc 1% Oil Control Serum',
                'brand': 'The Ordinary',
                'description': 'High-strength vitamin and mineral blemish formula. Reduces skin blemishes, balances visible sebum activity, and smooths skin texture.',
                'price': Decimal('600.00'),
                'category': 'beauty',
                'stock': 100,
                'is_featured': False,
                'discount_percent': 0,
                'rating': Decimal('4.6'),
            },
            {
                'name': 'CeraVe Hydrating Facial Cleanser for Normal to Dry Skin 473ml',
                'brand': 'CeraVe',
                'description': 'Developed with dermatologists. Formulated with 3 essential ceramides and hyaluronic acid to cleanse and hydrate without disrupting skin\'s natural protective barrier.',
                'price': Decimal('1450.00'),
                'category': 'beauty',
                'stock': 65,
                'is_featured': False,
                'discount_percent': 12,
                'rating': Decimal('4.7'),
            },

            # 8. Toys & Games (5 items)
            {
                'name': 'LEGO Icons Concorde Supersonic Aircraft Model 10318',
                'brand': 'LEGO',
                'description': 'Detailed 2,083-piece replica model featuring droop nose, functioning landing gear, retractable tail bumper wheel, and accessible passenger cabin.',
                'price': Decimal('19999.00'),
                'category': 'toys',
                'stock': 12,
                'is_featured': True,
                'discount_percent': 10,
                'rating': Decimal('4.9'),
            },
            {
                'name': 'Catan Board Game (5th Edition)',
                'brand': 'Asmodee',
                'description': 'The classic strategy game of trading, building, and settling. Picture yourself in the era of discoveries: explore the uncharted isle of Catan with friends and family.',
                'price': Decimal('3499.00'),
                'category': 'toys',
                'stock': 40,
                'is_featured': False,
                'discount_percent': 20,
                'rating': Decimal('4.8'),
            },
            {
                'name': 'DJI Neo Ultralight Palm-Takeoff 4K Drone',
                'brand': 'DJI',
                'description': 'Only 135g palm-sized drone with AI subject tracking, QuickShots, 4K ultra-stabilized video, and full-coverage propeller guards for ultra-safe flying.',
                'price': Decimal('22990.00'),
                'category': 'toys',
                'stock': 25,
                'is_featured': False,
                'discount_percent': 12,
                'rating': Decimal('4.7'),
            },
            {
                'name': 'Rubik\'s Speed Cube Magnetic 3x3 Tournament Edition',
                'brand': 'Rubik\'s',
                'description': 'Built with internal positioning magnets and adjusted spring elasticity for lightning-fast corner cutting without popping or locking.',
                'price': Decimal('1299.00'),
                'category': 'toys',
                'stock': 80,
                'is_featured': False,
                'discount_percent': 25,
                'rating': Decimal('4.5'),
            },
            {
                'name': 'Hot Wheels Super Ultimate Garage Motorized Playset',
                'brand': 'Hot Wheels',
                'description': 'Over 3 feet tall with parking for 140+ cars. Features a motorized elevator that transports up to 23 cars at a time and a menacing robotic gorilla.',
                'price': Decimal('14999.00'),
                'category': 'toys',
                'stock': 10,
                'is_featured': False,
                'discount_percent': 18,
                'rating': Decimal('4.6'),
            },

            # 9. Automotive & Tools (5 items)
            {
                'name': 'Bosch Professional Cordless Drill Driver GSR 120-LI',
                'brand': 'Bosch',
                'description': 'Affordable power with 2-speed gearbox and Electronic Cell Protection (ECP) for longer battery life. Includes 2x 2.0Ah batteries, charger, and sturdy carry case.',
                'price': Decimal('5499.00'),
                'category': 'automotive',
                'stock': 30,
                'is_featured': False,
                'discount_percent': 22,
                'rating': Decimal('4.6'),
            },
            {
                'name': '70mai A810 4K HDR Dash Cam with Sony Starvis 2 Sensor',
                'brand': '70mai',
                'description': 'True 4K UHD recording with front 60FPS, built-in GPS, ADAS safety alerts, 24-hour parking surveillance, and exceptional night vision.',
                'price': Decimal('13999.00'),
                'category': 'automotive',
                'stock': 22,
                'is_featured': True,
                'discount_percent': 15,
                'rating': Decimal('4.7'),
            },
            {
                'name': 'Kärcher K3 High Pressure Washer 120 Bar',
                'brand': 'Kärcher',
                'description': 'Ideal for regular car washes, patio cleaning, and outdoor furniture. Includes Vario Power spray lance, Dirt Blaster, and 6-meter high-pressure hose.',
                'price': Decimal('11499.00'),
                'category': 'automotive',
                'stock': 18,
                'is_featured': False,
                'discount_percent': 20,
                'rating': Decimal('4.5'),
            },
            {
                'name': 'Michelin Digital Tyre Inflator with High Accuracy Gauge',
                'brand': 'Michelin',
                'description': 'Inflates a standard 13" tire from 0 to 35 PSI in under 3 minutes. White digital LCD screen with auto-stop preset pressure function and bright LED worklight.',
                'price': Decimal('4299.00'),
                'category': 'automotive',
                'stock': 45,
                'is_featured': False,
                'discount_percent': 18,
                'rating': Decimal('4.6'),
            },
            {
                'name': 'Wera Kraftform Kompakt 27 Screwdriver with Bit Magazine',
                'brand': 'Wera',
                'description': 'Ergonomic Kraftform multi-component handle with built-in spring-loaded magazine holding 6 high-durability torsion bits and strong magnetic bit holder.',
                'price': Decimal('3250.00'),
                'category': 'automotive',
                'stock': 50,
                'is_featured': False,
                'discount_percent': 10,
                'rating': Decimal('4.8'),
            },

            # 10. Gourmet & Grocery (5 items)
            {
                'name': 'Blue Tokai Coffee Roasters Vienna Roast Dark Coffee Beans 1kg',
                'brand': 'Blue Tokai',
                'description': '100% Specialty Grade Arabica coffee freshly roasted with notes of dark chocolate, toasted nuts, and oak. Roasted with care in micro-batches.',
                'price': Decimal('1650.00'),
                'category': 'grocery',
                'stock': 60,
                'is_featured': False,
                'discount_percent': 10,
                'rating': Decimal('4.8'),
            },
            {
                'name': 'Lindt Excellence 85% Cocoa Dark Chocolate 100g (Pack of 5)',
                'brand': 'Lindt',
                'description': 'Full-bodied, intense dark chocolate crafted by Lindt Master Chocolatiers using the finest cocoa beans from sustainable agricultural sources.',
                'price': Decimal('1499.00'),
                'category': 'grocery',
                'stock': 70,
                'is_featured': False,
                'discount_percent': 15,
                'rating': Decimal('4.7'),
            },
            {
                'name': 'Borges Extra Virgin Olive Oil 2 Litre Tin',
                'brand': 'Borges',
                'description': 'First cold-pressed extra virgin olive oil made from olives harvested in Spain. Retains rich aroma, low acidity (<0.5%), and beneficial polyphenols.',
                'price': Decimal('2899.00'),
                'category': 'grocery',
                'stock': 40,
                'is_featured': False,
                'discount_percent': 20,
                'rating': Decimal('4.6'),
            },
            {
                'name': 'Twinings Pure Green Tea Bags 100 Envelopes',
                'brand': 'Twinings',
                'description': 'Delicate, refreshing green tea crafted from tender steamed tea leaves. Naturally rich in antioxidants with a smooth, non-bitter golden brew.',
                'price': Decimal('899.00'),
                'category': 'grocery',
                'stock': 90,
                'is_featured': False,
                'discount_percent': 12,
                'rating': Decimal('4.5'),
            },
            {
                'name': 'Happilo 100% Raw California Almonds 1kg Value Pack',
                'brand': 'Happilo',
                'description': 'Non-GMO crunchy whole almonds packed with Vitamin E, plant protein, and healthy fats. Vacuum sealed for peak freshness and crunch.',
                'price': Decimal('999.00'),
                'category': 'grocery',
                'stock': 85,
                'is_featured': False,
                'discount_percent': 25,
                'rating': Decimal('4.6'),
            },

            # 11. Office & Stationery (5 items)
            {
                'name': 'Lamy Safari Fountain Pen Charcoal Black Medium Nib',
                'brand': 'Lamy',
                'description': 'Timeless modern design made from sturdy ABS plastic with ergonomic grip zone and spring-action chrome metal clip. Made in Heidelberg, Germany.',
                'price': Decimal('2890.00'),
                'category': 'stationery',
                'stock': 45,
                'is_featured': False,
                'discount_percent': 10,
                'rating': Decimal('4.8'),
            },
            {
                'name': 'Moleskine Classic Hardcover Dotted Notebook XL Black',
                'brand': 'Moleskine',
                'description': '192 acid-free pages of 70gsm ivory paper. Features rounded corners, ribbon bookmark, elastic band closure, and expandable inner rear pocket.',
                'price': Decimal('1995.00'),
                'category': 'stationery',
                'stock': 60,
                'is_featured': False,
                'discount_percent': 15,
                'rating': Decimal('4.7'),
            },
            {
                'name': 'Fellowes Powershred 8Cd Cross-Cut Paper Shredder',
                'brand': 'Fellowes',
                'description': 'Shreds up to 8 sheets at once into 4x35mm particles (Security Level P-4). Safely destroys credit cards, CDs, and paper clips with patented Safety Lock.',
                'price': Decimal('7499.00'),
                'category': 'stationery',
                'stock': 15,
                'is_featured': False,
                'discount_percent': 18,
                'rating': Decimal('4.4'),
            },
            {
                'name': 'Epson EcoTank L3250 Wi-Fi All-in-One Ink Tank Printer',
                'brand': 'Epson',
                'description': 'Ultra-low-cost printing with spill-free ink bottles. Up to 4,500 pages black and 7,500 pages color per refill. Smart Wi-Fi direct and mobile printing.',
                'price': Decimal('14999.00'),
                'category': 'stationery',
                'stock': 20,
                'is_featured': True,
                'discount_percent': 14,
                'rating': Decimal('4.6'),
            },
            {
                'name': 'BenQ WiT e-Reading LED Desk Lamp with Auto-Dimming',
                'brand': 'BenQ',
                'description': 'Curved lighting arc delivers 150% wider lighting area than traditional desk lamps. Built-in ambient light sensor automatically adjusts brightness for monitors.',
                'price': Decimal('18990.00'),
                'category': 'stationery',
                'stock': 12,
                'is_featured': False,
                'discount_percent': 10,
                'rating': Decimal('4.9'),
            },

            # 12. Gaming & Consoles (6 items)
            {
                'name': 'Sony PlayStation 5 Slim Console Disc Edition',
                'brand': 'PlayStation',
                'description': 'Harness the power of a custom CPU, GPU, and SSD with Integrated I/O that rewrite the rules of what a PlayStation console can do. Includes DualSense Wireless Controller.',
                'price': Decimal('54990.00'),
                'category': 'gaming',
                'stock': 15,
                'is_featured': True,
                'discount_percent': 5,
                'rating': Decimal('4.9'),
            },
            {
                'name': 'Nintendo Switch OLED Model with White Joy-Con',
                'brand': 'Nintendo',
                'description': 'Vibrant 7-inch OLED screen with deep blacks and vivid colors. Wide adjustable stand, wired LAN port in dock, 64GB internal storage, and enhanced audio.',
                'price': Decimal('31990.00'),
                'category': 'gaming',
                'stock': 20,
                'is_featured': True,
                'discount_percent': 10,
                'rating': Decimal('4.8'),
            },
            {
                'name': 'Xbox Wireless Controller Robot White',
                'brand': 'Xbox',
                'description': 'Sculpted surfaces and refined geometry for enhanced comfort during gameplay. Hybrid D-pad and textured grip on triggers, bumpers, and back-case.',
                'price': Decimal('5390.00'),
                'category': 'gaming',
                'stock': 40,
                'is_featured': False,
                'discount_percent': 12,
                'rating': Decimal('4.7'),
            },
            {
                'name': 'SteelSeries Arctis Nova Pro Wireless Multi-System Headset',
                'brand': 'SteelSeries',
                'description': 'Almighty Audio with Premium High Fidelity drivers and 360° Spatial Audio. Active Noise Cancellation with dual USB multi-system connect and hot-swap battery system.',
                'price': Decimal('34999.00'),
                'category': 'gaming',
                'stock': 14,
                'is_featured': False,
                'discount_percent': 15,
                'rating': Decimal('4.8'),
            },
            {
                'name': 'Razer BlackWidow V4 Pro RGB Mechanical Gaming Keyboard',
                'brand': 'Razer',
                'description': 'Green mechanical clicky switches, 8 dedicated macro keys, multi-function roller and 4 media keys, magnetic plush leatherette wrist rest with underglow.',
                'price': Decimal('22999.00'),
                'category': 'gaming',
                'stock': 18,
                'is_featured': False,
                'discount_percent': 18,
                'rating': Decimal('4.6'),
            },
            {
                'name': 'Elgato Stream Deck MK.2 – 15 Customizable LCD Keys',
                'brand': 'Elgato',
                'description': '15 customizable LCD keys to control apps, tools, and platforms. One-touch tactile operation, detachable stand, and interchangeable faceplates for streamers and power users.',
                'price': Decimal('14499.00'),
                'category': 'gaming',
                'stock': 25,
                'is_featured': False,
                'discount_percent': 10,
                'rating': Decimal('4.8'),
            },
        ]

        created_count = 0
        updated_count = 0
        for product_data in products:
            obj, created = Product.objects.update_or_create(
                name=product_data['name'],
                defaults=product_data,
            )
            if created:
                created_count += 1
            else:
                updated_count += 1

        self.stdout.write(
            self.style.SUCCESS(
                f'Successfully seeded catalog: {created_count} created, {updated_count} updated ({len(products)} total catalog items)'
            )
        )
