# Generated by Django 5.2.17 on 2026-08-15 16:09

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('products', '0003_product_brand_alter_product_category_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='discount_savings',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total saved by customer', max_digits=12),
        ),
        migrations.AddField(
            model_name='order',
            name='original_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total before discount', max_digits=12),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('card', 'Credit / Debit Card (Demo)'), ('upi', 'Instant UPI / QR (Demo)'), ('netbanking', 'Net Banking (Demo)'), ('cod', 'Cash on Delivery (Demo)')], default='card', max_length=30),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('paid', 'Paid (Demo Simulation)'), ('pending', 'Payment Pending'), ('cancelled', 'Cancelled / Void'), ('refunded', 'Refunded (Demo Simulation)')], default='paid', max_length=30),
        ),
        migrations.AddField(
            model_name='order',
            name='transaction_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='discount_percent',
            field=models.PositiveIntegerField(default=0, help_text='Discount percent at purchase'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='original_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Original list price per unit', max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('return_requested', 'Return Requested'), ('returned', 'Returned'), ('refunded', 'Refunded')], default='pending', max_length=30),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, help_text='Final payable amount after discounts', max_digits=12),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price_at_purchase',
            field=models.DecimalField(decimal_places=2, help_text='Sale price paid per unit', max_digits=10),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product'),
        ),
    ]
